/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.

  //skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  //skycons.add("day1", Skycons.CLEAR_DAY);
  //skycons.add("day2", Skycons.CLOUDY);
  //skycons.add("day3", Skycons.RAIN);


  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  //ßskycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
  var selected=$(this).text().slice(0,3);
  $("button").text(selected);
  WData(selected);
    //alert(selected);

});


function WData(CityName){
  var api="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+CityName+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
  $.getWeatherJSON(api,function(data){
  	// 可以比較方便找到你要的資料在這個物件的哪個位置
  	console.log (data) ;

  	var currentTemperature = data.query.results.channel.item.condition.temp  ;
    console.log (currentTemperature) ;
    $(".temperature").text(Math.round((currentTemperature-32)*5/9));
    var currentDate = data.query.results.channel.lastBuildDate  ;
    console.log (currentDate) ;
    $(".date").text(currentDate);
    var currentWeather = data.query.results.channel.item.condition.text  ;
    console.log (currentWeather) ;
    $(".weather").text(currentWeather);
    var Dayd1 = data.query.results.channel.item.forecast[1].date;
    console.log (Dayd1) ;
    $(".d1").text(Dayd1);
    var Dayd2 = data.query.results.channel.item.forecast[2].date;
    console.log (Dayd2) ;
    $(".d2").text(Dayd2);
    var Dayd3 = data.query.results.channel.item.forecast[3].date;
    console.log (Dayd3) ;
    $(".d3").text(Dayd3);
    var Dayh1 = data.query.results.channel.item.forecast[1].high;
    console.log (Dayh1) ;
    $(".hw1").text(Math.round((Dayh1-32)*5/9));
    var Dayh2 = data.query.results.channel.item.forecast[2].high;
    console.log (Dayh2) ;
    $(".hw2").text(Math.round((Dayh2-32)*5/9));
    var Dayh3 = data.query.results.channel.item.forecast[3].high;
    console.log (Dayh3) ;
    $(".hw3").text(Math.round((Dayh3-32)*5/9));
    var Dayl1 = data.query.results.channel.item.forecast[1].low;
    console.log (Dayl1) ;
    $(".l1").text(Math.round((Dayl1-32)*5/9));
    var Dayl2 = data.query.results.channel.item.forecast[2].low;
    console.log (Dayl2) ;
    $(".l2").text(Math.round((Dayl2-32)*5/9));
    var Dayl3 = data.query.results.channel.item.forecast[3].low;
    console.log (Dayl3) ;
    $(".l3").text(Math.round((Dayl3-32)*5/9));
    var Dayw1 = data.query.results.channel.item.forecast[1].text;
    console.log (Dayw1) ;
    $("#day1").text(Dayw1);
    var Dayw2 = data.query.results.channel.item.forecast[2].text;
    console.log (Dayw2) ;
    $("#day2").text(Dayw2);
    var Dayw3 = data.query.results.channel.item.forecast[3].text;
    console.log (Dayw3) ;
    $("#day3").text(Dayw3);

    skycons.set("today", con(currentWeather));
    skycons.set("day1", con(Dayw1));
    skycons.set("day2", con(Dayw2));
    skycons.set("day3", con(Dayw3));

    });
  }

  WData("Taipei City");


function con(Condition){


    if (Condition.indexOf("Night")>=0 && Condition.indexOf("Partly")>=0) {
          return Skycons.PARTLY_CLOUDY_NIGHT;}

            else if(Condition.indexOf("Partly Cloudy")>=0){
                  return Skycons.PARTLY_CLOUDY_DAY;}

            else if(Condition.indexOf("Cloudy")>=0){
                  return Skycons.CLOUDY;}

            else if(Condition.indexOf("Night")>=0){
                  return Skycons.CLEAR_NIGHT;}

            else if (Condition.indexOf("Clear")>=0 || Condition.indexOf("Sunny")>=0 || Condition.indexOf("Fair")>=0 || Condition.indexOf("Hot")>=0){
                  return Skycons.CLEAR_DAY;}

            else if (Condition.indexOf("Snow")>=0 || Condition.indexOf("Hail")>=0){
                  return Skycons.SNOW;}

            else if (Condition.indexOf("Drizzle")>=0 || Condition.indexOf("Sleet")>=0){
                  return Skycons.SLEET;}

            else if (Condition.indexOf("Rain")>=0 || Condition.indexOf("Showers")>=0 || Condition.indexOf("Thundershowers")>=0 ||Condition.indexOf("Thunderstorms")>=0){
                  return Skycons.RAIN;}

            else if (Condition.indexOf("Dust")>=0 || Condition.indexOf("Foggy")>=0 || Condition.indexOf("Haze")>=0 || Condition.indexOf("Smoky")>=0){
                  return Skycons.FOG;}

            else if (Condition.indexOf("Windy")>=0 || Condition.indexOf("Blustery")>=0 || Condition.indexOf("Tornado")>=0 || Condition.indexOf("Storm")>=0 || Condition.indexOf("Hurricane")>=0 || Condition.indexOf("Breezy")>=0 || Condition.indexOf("Cold")>=0){
                  return Skycons.WIND;}

}


function selectWT(){
  $('#dropdown li').each(function(index,element){
  var City=$(element).text().slice(0,3);
  var api="https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+City+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
  $.getJSON(api,function(data){
    var currentTemperature = data.query.results.channel.item.condition.temp  ;
    $(element).children("a").children(".CW").text(Math.round((currentTemperature-32)*5/9)+"℃");
    console.log(City);
  })
  $(".CW").css("float","right");
   })
}
 selectWT();
